// <auto-generated />
namespace EventManagement.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_audience_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_audience_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131040173_create_audience_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
