// <auto-generated />
namespace EventManagement.DB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_refresh_token_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_refresh_token_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201808120636483_create_refresh_token_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
